language: php
php:
  - 7.4
sudo: true
cache:
  directories:
    - $HOME/.composer/cache
services:
  - docker
script:
  - |
    set -e
    composer update --prefer-stable --no-interaction --no-suggest
    resources/build-docs.sh
deploy:
  provider: pages
  local_dir: site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master