language: php
php:
  - 7.4
sudo: true
env:
  global:
    - CC_TEST_REPORTER_ID=06f21fc365ca955657e0b5b6ce2f5c84533cb4e2de87ba0f3d0b016aaf40a1de
cache:
  directories:
    - $HOME/.composer/cache
services:
  - docker
before_script:
  - |
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
    chmod +x ./cc-test-reporter;
    ./cc-test-reporter before-build;
script:
  - |
    set -e;
    composer update --prefer-stable --no-interaction --no-suggest;
    composer cs;
    composer test-coverage;
    composer build-docs;
after_script:
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi;
deploy:
  provider: pages
  local_dir: site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master
