language: php
php:
  - 7.4
  - nightly
jobs:
  allow_failures:
    - php: nightly
sudo: true
env:
  global:
    - CC_TEST_REPORTER_ID=613b733b54821d91a3fe4dd2b408a08cd0bb3550ef88fb2bbad3400bcdd336dc
cache:
  directories:
    - $HOME/.composer/cache
services:
  - docker
before_script:
  - |
    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter;
    chmod +x ./cc-test-reporter;
    ./cc-test-reporter before-build;
script:
  - |
    set -e;
    composer update --prefer-stable --no-interaction --no-suggest;
    composer cs;
    composer test-coverage;
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]] && [[ $TRAVIS_PULL_REQUEST == "false" ]]; then composer build-docs; fi;
after_script:
  - |
    if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi;
deploy:
  provider: pages
  local_dir: site
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: gh-pages
  on:
    branch: master
