version: '3'

services:
  mkdocs:
    build:
      context: resources/docker/mkdocs-material
    image: dog/mkdocs-material
    volumes:
      - .:/docs
    ports:
      - 8000:8000

  php80:
    build:
      context: resources/docker/php80
    image: dog/php80
    volumes:
      - .:/app

  php81:
    build:
      context: resources/docker/php81
    image: dog/php81
    volumes:
      - .:/app

  php82:
    build:
      context: resources/docker/php82
    image: dog/php82
    volumes:
      - .:/app